"""gled2 installation SVG for the stella octangula.

Emits the SVG that gled (photonenkollektiv) loads as an installation: one
path per lamp, each carrying its patch — groups, start, count — as Hjson in a
``<desc>`` child, laid out as a classic isometric projection of the two
tetrahedra so all twelve lamps read as the well-known star without overlap.

The lamp axes, the wiring labels (``b0..b5``, ``o0..o5``) and the vertex
groups all come from ``led_profiles.assemblies.stella_octangula`` — this
package is a projection of the CAD, never a second source of it.

    uv run python -c "import models.gled2 as g; g.write()"
    uv run check gled2
"""

from __future__ import annotations

import json
from math import cos, radians, sin
from pathlib import Path

from models.led_profiles import config as c
from models.led_profiles.assemblies.stella_octangula import (
    LampSegment,
    lamp_segments,
)

# Addressable pixels per 1.5 m lamp, and DMX slots per pixel. The star-tent
# rigs stream 23 px per spoke at 3 slots each (beamhouse's reference rig
# consumes exactly that); if the stella's COB strips end up cut finer, change
# it here and regenerate both projects.
PIXELS_PER_LAMP = 23
CHANNELS_PER_PIXEL = 3

# gled's per-universe LED capacity: lamp LEDs past this spill into
# universe + 1 automatically, so the patch below needs no split logic.
LEDS_PER_UNIVERSE = 170

VERTEX_GROUPS = ("v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8")


def lamp_parameters(segment: LampSegment, index: int) -> dict:
    """The Hjson parameter set for one lamp path.

    Base tetra vertices are groups ``v1..v4``, the offset tetra's ``v5..v8`` —
    the two tetrahedra share no corners, so they share no vertex groups.
    """
    tetra_base = 4 if segment.tetra == "offset" else 0
    return {
        "groups": [
            segment.tetra,
            VERTEX_GROUPS[segment.vertices[0] + tetra_base],
            VERTEX_GROUPS[segment.vertices[1] + tetra_base],
        ],
        "start": index * PIXELS_PER_LAMP,
        "count": PIXELS_PER_LAMP,
    }


def _desc(parameters: dict) -> str:
    """A ``<desc>`` body: strict JSON, which is valid Hjson for gled's parser."""
    return json.dumps(parameters)


def _isometric(point) -> tuple[float, float]:
    """World millimetres (z up) to sheet coordinates (y down), cube isometry."""
    angle = radians(30.0)
    u = (point.X - point.Y) * cos(angle)
    v = (point.X + point.Y) * sin(angle) + point.Z
    return u, -v


def svg_text(length: float = c.LENGTH) -> str:
    """The whole installation as an SVG string, units in millimetres."""
    segments = lamp_segments(length)
    projected = []
    for segment in segments:
        u0, v0 = _isometric(segment.start)
        u1, v1 = _isometric(segment.end)
        projected.append((segment, u0, v0, u1, v1))
    points = [(u0, v0) for _, u0, v0, _, _ in projected] + [
        (u1, v1) for _, _, _, u1, v1 in projected
    ]
    pad = 120.0
    min_u = min(u for u, _ in points) - pad
    max_u = max(u for u, _ in points) + pad
    min_v = min(v for _, v in points) - pad
    max_v = max(v for _, v in points) + pad
    paths = [
        f'    <path id="{seg.name}" '
        f'd="M {u0:.2f} {v0:.2f} L {u1:.2f} {v1:.2f}">\n'
        f"      <desc>{_desc(lamp_parameters(seg, index))}</desc>\n"
        "    </path>"
        for index, (seg, u0, v0, u1, v1) in enumerate(projected)
    ]
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- stella octangula installation for gled, generated by"
        " models/gled2. Do not edit by hand. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{max_u - min_u:.0f}mm"'
        f' height="{max_v - min_v:.0f}mm" viewBox="{min_u:.0f} {min_v:.0f}'
        f' {max_u - min_u:.0f} {max_v - min_v:.0f}">\n'
        '  <g id="stella" fill="none" stroke="#111111"'
        ' stroke-width="12" stroke-linecap="round">\n'
        f"      <desc>{_desc({'groups': ['all'], 'universe': 0})}</desc>\n"
        + "\n".join(paths)
        + "\n  </g>\n</svg>\n"
    )


def write(
    path: str | Path = "exports/gled2-stella-octangula.svg", length: float = c.LENGTH
) -> Path:
    """Write the installation SVG, returning the path written."""
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(svg_text(length), encoding="utf-8")
    return destination
